# This file was generated by GoReleaser. DO NOT EDIT.
class Getparty < Formula
  desc "HTTP Download Manager with multi-parts"
  homepage "https://github.com/vbauerster/getparty"
  url "https://github.com/vbauerster/getparty/releases/download/v1.5.2/getparty_1.5.2_Darwin_x86_64.tar.gz"
  version "1.5.2"
  sha256 "f0d943d59feade6d3bee27aabe3eb2f29f0aa5e62c6e62fc99b06df7d75b6e2c"

  def install
    bin.install "getparty"
  end

  test do
    system  "#{bin}/getparty --version"
  end
end
