# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getparty < Formula
  desc "HTTP Download Manager with multi-parts"
  homepage "https://github.com/vbauerster/getparty"
  version "1.14.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vbauerster/getparty/releases/download/v1.14.1/getparty_1.14.1_darwin_arm64.tar.gz"
      sha256 "49d81cae704a30f5bfe53a359fccfa957ffe3530368c983bec7799d396f20a9e"

      def install
        bin.install "getparty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vbauerster/getparty/releases/download/v1.14.1/getparty_1.14.1_darwin_amd64.tar.gz"
      sha256 "24476ceeaf0cc0f87f4903d5328db6b0996ac4fcd178f548c67048403ccb19ad"

      def install
        bin.install "getparty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vbauerster/getparty/releases/download/v1.14.1/getparty_1.14.1_linux_amd64.tar.gz"
      sha256 "be9d3a783b7d4d0f32b6d1c5e9c3cdca9f5dc0b3289d94db9b6e5e9f5618e48d"

      def install
        bin.install "getparty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vbauerster/getparty/releases/download/v1.14.1/getparty_1.14.1_linux_arm64.tar.gz"
      sha256 "297b7b3d25bc13cc21301bfcf0b31cd3307677ca84d02f7b2288d6de51fd9249"

      def install
        bin.install "getparty"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/vbauerster/getparty/releases/download/v1.14.1/getparty_1.14.1_linux_armv6.tar.gz"
      sha256 "1eb9c698374445503c8eed266d21de5e8449a015b22351017631409f2f7c5623"

      def install
        bin.install "getparty"
      end
    end
  end

  test do
    system  "#{bin}/getparty --version"
  end
end
